### ISSUE TITLE
Get full quality

### ISSUE THREAD

**Issue by Muot** [KaranJain29/Google-Photo-Player-JW-Player-Integrated#1]
Hello im try to get video but can't find full quality, how to fix it.

**Comment by KaranJain29** [comment]
@Muot Currenlty getting full quality is not supported. Becuase if you try to get full quality and video stored on google photos doesn't have that quality then video would show error. So, users don't get error while changing to higher quality playback, default quality set is 360p.

**Comment by Muot** [comment]
Thanks you, good jobs bro. Code is working perfect!
